#ifndef CHOCO_V1_MAPPINGS_H
#define CHOCO_V1_MAPPINGS_H

#include <lib/keyboard/kb_mappings.h>

// LEFT:

RULES_FOR_SIMPLE_KEY(KEY00, KEY_FN);
RULES_FOR_SIMPLE_KEY(KEY01, KEY_ESCAPE);
RULES_FOR_SIMPLE_KEY(KEY02, KEY_LEFTALT);

RULES_FOR_KEY(KEY10) = {
    RULE(LAYER1, KEY_1_EXCLAMATION),
    RULE(LAYER0, KEY_Q),
};
RULES_FOR_KEY(KEY11) = {
    RULE(LAYER1, KEY_GRAVEACCENT_TILDE),
    RULE(LAYER0, KEY_A),
};
RULES_FOR_KEY(KEY12) = {
    RULE(LAYER0, KEY_Z),
};

RULES_FOR_KEY(KEY20) = {
    RULE(LAYER1, KEY_2_ATSIGN),
    RULE(LAYER0, KEY_W),
};
RULES_FOR_KEY(KEY21) = {
    RULE(LAYER1, KEY_SLASH_QUESTIONMARK),
    RULE(LAYER0, KEY_S),
};
RULES_FOR_KEY(KEY22) = {
    RULE(LAYER0, KEY_X),
};

RULES_FOR_KEY(KEY30) = {
    RULE(LAYER1, KEY_3_NUMBERSIGN),
    RULE(LAYER0, KEY_E),
};
RULES_FOR_KEY(KEY31) = {
    RULE(LAYER1, KEY_LEFTARROW),
    RULE(LAYER0, KEY_D),
};
RULES_FOR_KEY(KEY32) = {
    RULE(LAYER0, KEY_C),
};

RULES_FOR_KEY(KEY40) = {
    RULE(LAYER1, KEY_4_DOLLARSIGN),
    RULE(LAYER0, KEY_R),
};
RULES_FOR_KEY(KEY41) = {
    RULE(LAYER1, KEY_RIGHTARROW),
    RULE(LAYER0, KEY_F),
};
RULES_FOR_KEY(KEY42) = {
    RULE(LAYER0, KEY_V),
};

RULES_FOR_KEY(KEY50) = {
    RULE(LAYER1, KEY_5_PERCENTSIGN),
    RULE(LAYER0, KEY_T),
};
RULES_FOR_KEY(KEY51) = {
    RULE(LAYER1, KEY_SEMICOLON_COLON),
    RULE(LAYER0, KEY_G),
};
RULES_FOR_KEY(KEY52) = {
    RULE(LAYER0, KEY_B),
};

RULES_FOR_SIMPLE_KEY(KEY60, KEY_LAYER1);
RULES_FOR_SIMPLE_KEY(KEY61, KEY_LEFTSHIFT);
RULES_FOR_KEY(KEY62) = {
    RULE(LAYER0, KEY_SPACEBAR),
};
RULES_FOR_KEY(KEY63) = {
    RULE(LAYER0, KEY_TAB),
};

// RIGHT:

RULES_FOR_KEY(KEY70) = {
    RULE(LAYER0, KEY_BACKSPACE),
};
RULES_FOR_KEY(KEY71) = {
    RULE(LAYER0, KEY_ENTER),
};
RULES_FOR_SIMPLE_KEY(KEY72, KEY_LAYER1);
RULES_FOR_KEY(KEY73) = {
    RULE(LAYER0, KEY_LEFTCONTROL),
};

RULES_FOR_KEY(KEY80) = {
    RULE(LAYER1, KEY_6_CARET),
    RULE(LAYER0, KEY_Y),
};
RULES_FOR_KEY(KEY81) = {
    RULE(LAYER1, KEY_APOSTROPHE_QUOTES),
    RULE(LAYER0, KEY_H),
};
RULES_FOR_KEY(KEY82) = {
    RULE(LAYER0, KEY_N),
};

RULES_FOR_KEY(KEY90) = {
    RULE(LAYER1, KEY_7_AMPERSAND),
    RULE(LAYER0, KEY_U),
};
RULES_FOR_KEY(KEY91) = {
    RULE(LAYER1, KEY_UPARROW),
    RULE(LAYER0, KEY_J),
};
RULES_FOR_KEY(KEY92) = {
    RULE(LAYER0, KEY_M),
};

RULES_FOR_KEY(KEY100) = {
    RULE(LAYER1, KEY_8_STAR),
    RULE(LAYER0, KEY_I),
};
RULES_FOR_KEY(KEY101) = {
    RULE(LAYER1, KEY_DOWNARROW),
    RULE(LAYER0, KEY_K),
};
RULES_FOR_KEY(KEY102) = {
    RULE(LAYER0, KEY_COMMA_LESSTHAN),
};

RULES_FOR_KEY(KEY110) = {
    RULE(LAYER1, KEY_9_LPAREN),
    RULE(LAYER0, KEY_O),
};
RULES_FOR_KEY(KEY111) = {
    RULE(LAYER1, KEY_BACKSLASH_VERTICALBAR),
    RULE(LAYER0, KEY_L),
};
RULES_FOR_KEY(KEY112) = {
    RULE(LAYER0, KEY_DOT_GREATERTHAN),
};

RULES_FOR_KEY(KEY120) = {
    RULE(LAYER1, KEY_0_RPAREN),
    RULE(LAYER0, KEY_P),
};
RULES_FOR_KEY(KEY121) = {
    RULE(LAYER0, KEY_SQBRACKETL_CURBRACEL),
};
RULES_FOR_KEY(KEY122) = {
    RULE(LAYER0, KEY_SQBRACKETR_CURBRACER),
};

RULES_FOR_SIMPLE_KEY(KEY130, KEY_FN);
RULES_FOR_SIMPLE_KEY(KEY131, KEY_RIGHTALT);
RULES_FOR_SIMPLE_KEY(KEY132, KEY_RIGHTGUI);

// The sequence in which keys are mapped to the physical key sequence in kscan.
// Modify with caution

DEFAULT_KEYMAP_DEFINE(KEY(KEY50), KEY(KEY51), KEY(KEY52), KEY(KEY63),
                      KEY(KEY62), KEY(KEY61), KEY(KEY60), KEY(KEY40),
                      KEY(KEY41), KEY(KEY42), KEY(KEY30), KEY(KEY31),
                      KEY(KEY32), KEY(KEY20), KEY(KEY21), KEY(KEY22),
                      KEY(KEY10), KEY(KEY11), KEY(KEY12), KEY(KEY00),
                      KEY(KEY01), KEY(KEY02), KEY(KEY80), KEY(KEY81),
                      KEY(KEY82), KEY(KEY70), KEY(KEY71), KEY(KEY72),
                      KEY(KEY73), KEY(KEY90), KEY(KEY91), KEY(KEY92),
                      KEY(KEY100), KEY(KEY101), KEY(KEY102), KEY(KEY110),
                      KEY(KEY111), KEY(KEY112), KEY(KEY120), KEY(KEY121),
                      KEY(KEY122), KEY(KEY130), KEY(KEY131), KEY(KEY132));

#endif // CHOCO_V1_MAPPINGS_H
